config/routes.rb
Rails.application.routes.draw do

  get "/auth/google_login/callback" => "sessions#create"
  get "/auth/google_login", :as => :signin
  get "/signout" => "sessions#destroy", :as => :signout

  get 'welcome/index'
  root 'welcome#index'

  resources :groups, :only => [:index, :create, :destroy, :show] do
    resources :members, :only => [:create, :destroy] do
    end

    resources :grouping_sets, :only => [:new, :create, :show] do
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user

  has_many :members, foreign_key: :group_id
  has_many :grouping_sets, foreign_key: :group_id
end

app/models/grouping.rb
class Grouping < ActiveRecord::Base
  belongs_to :grouping_set

  belongs_to :member1, class_name: "Member"
  belongs_to :member2, class_name: "Member"
  belongs_to :member3, class_name: "Member"
  belongs_to :member4, class_name: "Member"
  belongs_to :member5, class_name: "Member"

  # convenience method
  def members
    [member1, member2, member3, member4, member5].reject { |e| e == nil }
  end
end

app/models/grouping_set.rb
class GroupingSet < ActiveRecord::Base
  belongs_to :group

  has_many :groupings, foreign_key: :grouping_set_id

  def displayed_title
    if title.empty?
      "My grouping"
    else
      title
    end
  end

  ###
   # Actually populate the current grouping sets with lots of groups
   # from the current member list.
  ###
  def populate
    group.members.each_slice(group_size).to_a.shuffle.each do |members|
      grouping = Grouping.new(:grouping_set => self)
      if members.count > 0
        grouping.member1 = members[0]
      end
      if members.count > 1
        grouping.member2 = members[1]
      end
      if members.count > 2
        grouping.member3 = members[2]
      end
      if members.count > 3
        grouping.member4 = members[3]
      end
      if members.count > 4
        grouping.member5 = members[4]
      end
      grouping.save
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups, foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/grouping_sets_controller.rb
class GroupingSetsController < ApplicationController
  def new
    @set = GroupingSet.new(:group => current_group)
  end

  def create
    @set = GroupingSet.new(set_params)
    @set.group = current_group
    @set.member_count = current_group.members.count
    @set.save

    # actually do the logic for groupings
    @set.populate

    redirect_to group_grouping_set_path @set.group, @set
  end

  def show
    @set = current_grouping_set
  end

  private
    def current_group
      Group.where(:id => params[:group_id], :user => current_user).first
    end

    def current_grouping_set
      GroupingSet.where(:id => params[:id], :group => current_group).first
    end

    def set_params
      params.require(:grouping_set).permit(:group_size, :title, :description)
    end  

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
    @new_group = new_group
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    @group.save

    redirect_to group_path @group
  end

  def destroy
    @group = Group.where(:user => current_user, :id => params[:id])
    @group.destroy_all

    redirect_to groups_path
  end

  def show
    @group = current_group
    @new_member = Member.new(:group => @group)
  end

  private
    def new_group
      Group.new(:user => current_user)
    end

    def current_group
      Group.where(:user => current_user, :id => params[:id]).first
    end

    def group_params
      params.require(:group).permit(:title)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def create
    @member = Member.new(member_params)
    @member.group = current_group
    @member.save

    redirect_to group_path current_group
  end

  def destroy
    @member = Member.where(:group => current_group, :id => params[:id])
    @member.destroy_all

    redirect_to group_path current_group
  end  

  private
    def current_group
      Group.where(:id => params[:group_id], :user => current_user).first
    end

    def member_params
      params.require(:member).permit(:email, :group)
    end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth["provider"], :uid => auth["uid"]).first_or_initialize(
      :refresh_token => auth["credentials"]["refresh_token"],
      :access_token => auth["credentials"]["token"],
      :expires => auth["credentials"]["expires_at"],
      :name => auth["info"]["name"],
    )
    url = session[:return_to] || root_path
    session[:return_to] = nil
    url = root_path if url.eql?('/logout')

    if user.save
      session[:user_id] = user.id
      notice = "Signed in!"
      logger.debug "URL to redirect to: #{url}"
      redirect_to url, :notice => notice
    else
      raise "Failed to login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grouping_set_helper.rb
module GroupingSetHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/grouping_sets/new.html.haml
%h1 
  %small
    = link_to "Your Groups", groups_path
    \>
  %small
    = link_to @set.group.title, group_path(@set.group)
    \>
  Create a new set of coffee dates

= form_for [@set.group, @set] do |f|
  %li
    %label People

    = @set.group.members.count
    from
    = link_to @set.group.title, group_path(@set.group)

  %li
    = f.label :group_size

    %ul
      %li
        = f.radio_button :group_size, 2
        = f.label :group_size_2, '2'

      %li
        = f.radio_button :group_size, 3, :checked => true
        = f.label :group_size_3, '3'

      %li
        = f.radio_button :group_size, 4
        = f.label :group_size_4, '4'

  %li
    = f.label :title
    = f.text_field :title
    %i.optional (optional)

  %li
    = f.label :description
    = f.text_area :description
    %i.optional (optional)

  %li
    = f.submit

app/views/grouping_sets/show.html.haml
%h1 
  %small
    = link_to "Your Groups", groups_path
    \>
  %small
    = link_to @set.group.title, group_path(@set.group)
    \>
  = @set.displayed_title

%p
  Set up 
  = @set.created_at
  with
  = @set.member_count
  people from
  = link_to @set.group.title, group_path(@set.group)

%p.description
  = @set.description

%h2 Groups

%ul
  - @set.groupings.each do |grouping|
    %li 
      %ul
        - grouping.members.each do |member|
          %li
            = member.email

      %a.btn send reminder

app/views/groups/index.html.haml
%h1 Your Groups

%ul
  - @groups.each do |group|
    %li 
      = link_to group.title, group_path(group)

      = link_to "delete", group_path(group), :method => :delete

  %li
    = form_for @new_group do |f|
      = f.label :title
      = f.text_field :title

      = f.submit

app/views/groups/show.html.haml
%h1 
  %small
    = link_to "Your Groups", groups_path
    \>
  = @group.title

%h2 Sets of coffee dates

%ul
  - @group.grouping_sets.each do |set|
    %li
      = link_to set.displayed_title, group_grouping_set_path(set.group, set)
  - if @group.grouping_sets.empty?
    %li
      %i None so far!

  %li
    = link_to "Create a new set of coffee dates", new_group_grouping_set_path(@group)

%h2 Members

%ul
  - @group.members.each do |member|
    %li 
      %code
        = member.email

      = link_to "delete", group_member_path(member.group, member), :method => :delete
  - if @group.members.empty?
    %li
      %i You should add at least one e-mail address!

  %li
    = form_for [@group, @new_member] do |f|
      = f.label :email
      = f.email_field :email

      = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeedate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="controller-<%= controller.controller_name %> action-<%= controller.action_name %>">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.haml
%img.banner

%h1 Coffee Date

%h2.tagline
  Set up regular coffee meetings with your staff, clients or friends.

- if current_user
  Hi, #{current_user.name}!
  = link_to "Your groups", groups_path
  = link_to "Sign out", signout_path
- else
  = link_to "Sign in with Google", signin_path